### ISSUE TITLE
Break read

### ISSUE THREAD

**Issue by sinurb** [laurynas/volvo_linbus#1]
Hi,

I see in your code, you don't read the 13 bits "break" in LIN frame, how does it work then?

Thanks

**Comment by wchpikus** [comment]
Hi
Could you comfir, that master always send frame to key with id=0x20 and then keys answer?
And other question,where is the master lin? On the icm?

**Comment by laurynas** [comment]
Missed the question, sorry. I just used [LINBUS frame analyzer code](https://github.com/zapta/linbus/tree/master/analyzer/arduino). I split frames using SYN field:
https://github.com/laurynas/volvo_linbus/blob/master/volvo_linbus.ino#L66
