### ISSUE TITLE
lin bus isue

### ISSUE THREAD

**Issue by wchpikus** [laurynas/volvo_linbus#2]
Hello.
Did you know that icm is master of lin?
I trying different chip but no success

**Comment by iDoka** [comment]
My assumption:
steering wheel buttons are master on LIN-bus

**Comment by wchpikus** [comment]
ok, i test and know..icm as master..
buttons are slave.

**Comment by laurynas** [comment]
Yes, looks like [ICM is the master](https://f01.justanswer.com/rmldaytona/456ac45a-4c24-442e-8600-86b9e86ad75d_alt.pdf)
